### ISSUE TITLE
List of Plugins

### ISSUE THREAD

**Issue by aagoodman** [glue-viz/glue-viz.github.io#1]
We need to maintain a prominent live list of plugins, organized by field and/or functionality--maybe a faceted list so people can see either.  Tom can give a starter list.

**Comment by astrofrog** [comment]
I originally thought this should go in the documentation but now I agree it should go on the website - I think we should have a 'Plugins' link in the main menu bar.

**Comment by astrofrog** [comment]
Fixed by @sarahb55 in #4 - thanks!
